package-as: Kui_Nameplates

enable-nolib-creation:
    no

move-folders:
    Kui_Nameplates/Kui_Media: Kui_Media
    Kui_Nameplates/Kui_Nameplates_Core: Kui_Nameplates_Core
    Kui_Nameplates/Kui_Nameplates_Core_Config: Kui_Nameplates_Core_Config
    Kui_Nameplates/Kui_Nameplates: Kui_Nameplates

ignore:
    - .editorconfig
    - .gitignore
    - .luacheckrc
    - .externals
    - changelog
    - README.md
    - examples
    - dev
    - cspell.json
